model: conv2d
input_format: 'bchw'
batch_size: [1, 2, 4, 8, 16, 32, 64]
num_layers: [1]
img_size: [7, 14, 28, 56, 112, 224]
in_channels: [32, 64, 128, 256, 512, 1024]
out_channels: [32, 64, 128, 256, 512, 1024]
kernel_size: [1, 3]
stride: [1, 2, 5]
act_fn: "relu"
dropout: null
