model: feedforward
input_format: 'bsh'
batch_size: [1, 2, 4, 8, 16, 32, 64]
seq_len: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
num_layers: [1, 2, 4, 8, 16]
hidden_size: [1, 2, 4, 8, 16, 32, 64, 256, 512, 1024, 2048, 3072, 4096]
act_fn: relu
iters: 10
dropout: null
device_idx: null
