MaxPowerUsage: NA
OS: ubuntu2004
Isa: x86
Cpu: Intel Xeon W-2295
CudaArchitecture: NA
AcceleratorAvailable: NA
CpuCores: 36
GpuCores: 0
CpuClockSpeed: 3e9
GpuClockSpeed: 0
MemoryFrequency: 2.67e9
MemoryBandwidth: 19.9e9
Ram: 128
Vram: 0
