MaxPowerUsage: NA
OS: ubuntu2004
Isa: x86
Cpu: Intel Xeon W-2295
CudaArchitecture: turing
AcceleratorAvailable: true
CpuCores: 36
GpuCores: 4608
CpuClockSpeed: 3e9
GpuClockSpeed: 1.5e9
MemoryFrequency: 2.67e9
MemoryBandwidth: 19.9e9
Ram: 128
Vram: 48
