MaxPowerUsage: 10
OS: ubuntu1804
Isa: aarm64
Cpu: Cortex-A57
CudaArchitecture: NA
AcceleratorAvailable: NA
CpuCores: 4
GpuCores: 0
CpuClockSpeed: 1.5e9
GpuClockSpeed: 0
MemoryFrequency: 1.6e9
MemoryBandwidth: 6.9e9
Ram: 4
Vram: 0
