device_name: laptop
MaxPowerUsage: 45
OS: ubuntu2104
ISA: x86
Cpu: Intel i7-8550U
CudaArchitecture: null
AcceleratorAvailable: False
CpuCores: 8
GpuCores: null
CpuClockSpeed: 1.8e9
GpuClockSpeed: 0
MemorySpeed: 2.13e9
MemoryBandwidth: 11.36e9
Ram: 16
Vram: null
